PRELIMINARY: CI and Runtime: Add Erlang/OTP 28 to the versions matrix
Problems triggered by this change:

CI: string syntax "28" not yet supported by setup-beam

CI: 28.0-rc2: rebar3 binary included with ejabberd doesn't support 28
Runtime: 28: rebar3: rebar3 binary included with ejabberd doesn't support 28

Runtime: 28: rebar:
ERROR: generate failed while processing /__w/ejabberd/ejabberd/rel:
 {'EXIT',{{badmatch,{error,"Application et is used
 in release \"ejabberd\" and cannot be excluded"}},